#version 450

layout(local_size_x = 64, local_size_y = 1, local_size_z = 1) in;

layout(set = 0, binding = 0) buffer Weights {
    float w[];
};
layout(set = 1, binding = 0) buffer Input {
    float x[];
};
layout(set = 1, binding = 1) buffer Output {
    float output_vec[];
};

layout(push_constant) uniform Constants {
    uint layer;
    uint in_dim;
    uint out_dim;
    uint pos;
    uint weight_offset;
} pc;

void main() {
    uint row = gl_GlobalInvocationID.x;
    if (row >= pc.out_dim) return;

    float sum = 0.0;
    uint row_weight_offset = pc.weight_offset + (row * pc.in_dim);

    for (uint col = 0; col < pc.in_dim; ++col) {
        sum += w[row_weight_offset + col] * x[col];
    }

    output_vec[row] = sum;
}
